language: go

go:
  - 1.4

install: true

script:
  - ./goad init
  - ./goad validate
  - ./goad install
  - ./goad test

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net##polydawn"
    on_success: always
    on_failure: always
    template:
      - "%{repository_name}: %{commit} on %{branch} by %{author}: %{result}. %{build_url} %{commit_message}"
    skip_join: true
